const mongoose = require("mongoose")

const branchSchema = mongoose.Schema({
    allBranches_branch_name: { type: String },
    allBranches_branch_status: { type: String },
    allBranches_address_1: { type: String },
    allBranches_address_2: { type: String },
    allBranches_city: { type: String },
    allBranches_State: { type: String },
    allBranches_Zip: { type: String },
    allBranches_Phone: { type: String },
    allBranches_Fax: { type: String },
    allBranches_TimeZone: { type: String },
    allBranches_DST: { type: String },
    allBranches_GLAccountCode: { type: String },
    allBranches_Hierarchy: { type: String },
    allBranches_Email: { type: String },

    branches_billing: [{
        allBranches_billing_revenues_follow_branch: { type: String },
    }],

    branches_payroll: [{
        allBranches_check_process_method: { type: String },
        allBranches_eft_process_method: { type: String },
        allBranches_use_separate_check_batches: { type: String },
        allBranches_next_check_number: { type: String },
        allBranches_week_begins: { type: String },
        allBranches_default_payroll_company: { type: String },
        allBranches_default_payroll_departments: { type: String },
        allBranches_enable_registrant_w4: { type: String },
        allBranches_enable_registrant_1099: { type: String },
        allBranches_allow_w4_and_1099: { type: String },
        allBranches_enable_advance_pay: { type: String },
        allBranches_overtime_rule: { type: String },
        allBranches_oncall_rule: { type: String },
        allBranches_exclude_branch_from_exports: { type: String },
        allBranches_format_jp_morgan: { type: String },
        allBranches_location_code: { type: String },
        allBranches_muncipality: { type: String },
        allBranches_school_district: { type: String },
        allBranches_remittance_information: { type: String },
        allBranches_glaccount1: { type: String },
        allBranches_glaccount2: { type: String },
        allBranches_glaccount3: { type: String },
        allBranches_bankrouting1: { type: String },
        allBranches_bankrouting2: { type: String },
        allBranches_bankaccounts1: { type: String },
        allBranches_bankaccounts2: { type: String },
        allBranches_bank_name1: { type: String },
        allBranches_bank_name2: { type: String },
        allBranches_bank_number1: { type: String },
        allBranches_bank_number2: { type: String },
    }],

    branches_checklayout: [{
        allBranches_top_margin1: { type: String },
        allBranches_top_margin2: { type: String },
        allBranches_top_margin3: { type: String },
        allBranches_top_margin4: { type: String },
        allBranches_bottom_margin1: { type: String },
        allBranches_bottom_margin2: { type: String },
        allBranches_bottom_margin3: { type: String },
        allBranches_bottom_margin4: { type: String },
        allBranches_height1: { type: String },
        allBranches_height2: { type: String },
        allBranches_height3: { type: String },
        allBranches_height4: { type: String },
        allBranches_width1: { type: String },
        allBranches_width2: { type: String },
        allBranches_width3: { type: String },
        allBranches_width4: { type: String },
    }],

    branches_invoicing: [{
        allBranches_invoicing_use_agency_invoice_profile: { type: String },
        allBranches_invoicing_invoice_profile: { type: String },
        allBranches_invoicing_use_separate_print_queue_entries_for_this_branch: { type: String },
        allBranches_invoicing_school_district: { type: String },
        allBranches_invoicing_email_reply_to_address: { type: String },
        allBranches_invoicing_invoice_email_template: { type: String },
        allBranches_invoicing_remittance_information: { type: String }
    }],

    branches_registry: [{
        allBranches_email_time: { type: String },
    }],

    branches_scheduling: [{
        allBranches_order_entry: { type: String },
        allBranches_Discipline: { type: String },
        allBranches_ppc_target_margin: { type: String },
        allBranches_minimum_allowed_margin: { type: String },
    }],
    
    branches_client: [{
    allBranches_client_week_start_time1: { type: String },
    allBranches_client_day1: { type: String },
    allBranches_client_overtime_rule1: { type: String },
    allBranches_client_oncall_rule: { type: String },
    allBranches_client_overtime_rule2: { type: String },
    allBranches_client_week_start_time2: { type: String },
    allBranches_client_day2: { type: String },
    allBranches_client_weekend_start_time: { type: String },
    allBranches_client_day3: { type: String },
    allBranches_client_weekend_end_time: { type: String },
    allBranches_client_day4: { type: String },
    allBranches_client_split_shifts: { type: String },
    allBranches_client_split_weekends: { type: String },
    allBranches_client_split_holidays: { type: String },
    allBranches_client_bill_modifiers_ot1: { type: String },
    allBranches_client_bill_modifiers_ot2: { type: String },
    allBranches_client_bill_modifiers_dbl1: { type: String },
    allBranches_client_bill_modifiers_dbl2: { type: String },
    allBranches_client_bill_modifiers_holdiay1: { type: String },
    allBranches_client_bill_modifiers_holiday2: { type: String },
    allBranches_client_bill_modifiers_max1: { type: String },
    allBranches_client_bill_modifiers_max2: { type: String },
    allBranches_client_pay_modifiers_clients_ot3: { type: String },
    allBranches_client_pay_modifiers_clients__ot4: { type: String },
    allBranches_client_pay_modifiers_clients__dbl3: { type: String },
    allBranches_client_pay_modifiers_clients__dbl4: { type: String },
    allBranches_client_pay_modifiers_clients__holiday3: { type: String },
    allBranches_client_pay_modifiers_clients__holiday4: { type: String },
    allBranches_client_pay_modifiers_clients__max3: { type: String },
    allBranches_client_pay_modifiers_clients__max4: { type: String },
    allBranches_client_faculty_cancel_defaults_dbl5: { type: String },
    allBranches_client_faculty_cancel_defaults_dbl6: { type: String },
    allBranches_client_faculty_cancel_defaults_holiday5: { type: String },
    allBranches_client_faculty_cancel_defaults_holiday6: { type: String },
    allBranches_client_agency_cancel_defaults_dbl7: { type: String },
    allBranches_client_agency_cancel_defaults_dbl8: { type: String },
    allBranches_client_agency_cancel_defaults_holiday7: { type: String },
    allBranches_client_agency_cancel_defaults_holiday8: { type: String },
}]
})

module.exports = mongoose.model("BrancheModel", branchSchema)