const mongoose = require("mongoose")

const earningDeductionSchema = mongoose.Schema({
    earning_deduction_enabled: {type: String},
    earning_deduction_for_travel_contracts: {type: String},
    earning_deduction_name: {type: String},
    earning_deduction_desc: {type: String},
    earning_deduction_type: {type: String},
    earning_deduction_deduction_type: {type: String},
    earning_deduction_benefit_type: {type: String},
    earning_deduction_w2_box_12_code: {type: String},
    earning_deduction_include_with_paid_leave: {type: String},
    earning_deduction_required: {type: String},
    earning_deduction_billing_revenue_gl_account: {type: String},
    earning_deduction_calculation_method: {type: String},
    earning_deduction_calculation_method1: {type: String},
    earning_deduction_positive_or_negative: {type: String},
    earning_deduction_positive_or_negative1: {type: String},
    earning_deduction_frequency: {type: String},
    earning_deduction_frequency1: {type: String},
    earning_deduction_adjustment: {type: String},
    earning_deduction_adjustment1: {type: String},
    earning_deduction_editable: {type: String},
    earning_deduction_editable1: {type: String},
    earning_deduction_maximum_hours: {type: String},
    earning_deduction_maximum_hours1: {type: String},
    earning_deduction_all_regions_and_branches: {type: String},
    earning_deduction_regions: {type: String},
    earning_deduction_branches: {type: String},
    earning_deduction_hours_based: {type: String},
    earning_deduction_referral1: {type: String},
    earning_deduction_hours_required: {type: String},
    earning_deduction_referral2: {type: String},
    earning_deduction_empty: {type: String},
    earning_deduction_referral3: {type: String},
})

module.exports = mongoose.model("earningDeductionScheme", earningDeductionSchema)